package(default_visibility = ["//visibility:public"])

cc_library(
    name = "glm",
    srcs = ["v0.9.9.2/glm/detail/glm.cpp"],
    hdrs = glob([
        "**/*.hpp",
        "**/*.inl",
        "**/*.h",
    ]),
    includes = ["v0.9.9.2"],
)
