package(default_visibility = ["//visibility:public"])

cc_library(
    name = "util",
    srcs = [
        "frame.cc",
        "key.cc",
        "scad.cc",
    ],
    hdrs = [
        "frame.h",
        "key.h",
        "scad.h",
        "util.h",
    ],
    deps = [
        "//glm",
    ],
)
